### ISSUE TITLE
Typo edit

### ISSUE THREAD

**Issue by meadoge** [khongsomeo/.github#1]
Some typos encountered, and I hope you will fix soon:
- The heading of README is a typo.
- "suggest new fixture" is also a typo, "fixture" instead "feature"
- CoC link in CONTRIBUTION is false.
- CoC means __Code of Conduct__, not Code of Conduct(__s__).

These can be critical, please fix asap,

regards.

**Comment by trhgquan** [comment]
Problem encountered.
