### ISSUE TITLE
Requests / Bug reports are too long [ENHANCEMENT]

### ISSUE THREAD

**Issue by meadoge** [khongsomeo/.github#13]
I understand that making templates are hard, but those reports can be simpler since users just fucked up something and they wanted to report it asap. They don't want to spend minutes just to write an essay describing how they fucked up.

So, could report / request issue templates be made as simple as posible?. Thank you.

Tagging responsible team: @khongsomeo/dt101

**Comment by hwangswan** [comment]
Agreed that the bug report are too long, but these are just the "guide" so user can write what we could understand.

Anw, I'll have a look at it and do some changes. Thanks.
