### ISSUE TITLE
All bullets in issue templates should be removed [ENHANCEMENT]

### ISSUE THREAD

**Issue by trhgquan** [khongsomeo/.github#21]
# Enhancement Request

- __Project__: [khongsomeo/.github](https://github.com/khongsomeo/.github)

- __Tell us what to improve!__:

  All bullets make contents hard to format. We should remove those bullets.

- __Team mention__:

  @khongsomeo/dt101 .

**Comment by hwangswan** [comment]
Problem noticed.
