### ISSUE TITLE
Code of Conduct title is still wrong

### ISSUE THREAD

**Issue by meadoge** [khongsomeo/.github#3]
![Capture](https://user-images.githubusercontent.com/14867375/79628708-aa7da200-816d-11ea-9e86-8870ab1809cc.PNG)

You can give this to a team and get reviews. One-man army might not be useful in this situation.

**Comment by trhgquan** [comment]
Actually this was _not_ mentioned in the previous issue and since it was _not_ mentioned so I didn't see it too  :(

You can create a fix PR if you want, thanks!
